### ISSUE TITLE
[Feature] The most downloaded packages or The most popular packages

### ISSUE THREAD

**Issue by Heus-Sueh** [winget-run/web#114]
like this Featured packages
![image](https://user-images.githubusercontent.com/98482469/182942037-dc4a6ddd-c1a5-4cfe-9a66-90cb4e10b432.png)

**Comment by luxzg** [comment]
I know it's closed as not planned, but perhaps now that you have more statistical data, you could easily pull "Most viewed" list somewhere on the web? It was a good idea, hopefully it gets back on board eventually
