### ISSUE TITLE
Display package tags

### ISSUE THREAD

**Issue by Dragon1320** [winget-run/web#8]
Tags should be displayed on the package page and optionally on package cards. Will leave the optional part up for discussion.

**Comment by Dragon1320** [comment]
Card just on card page.

**Comment by Dragon1320** [comment]
@MattheousDT attach the designs pls

**Comment by MattheousDT** [comment]
https://xd.adobe.com/view/787d604b-6bda-4def-b65b-cddfb1d55378-2d2e/screen/d9ed27af-22bc-45ca-9b2a-f6d6fb121682/
